config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index]
  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :who_liked,  :class_name => "User"
  belongs_to :liked_pics, :class_name => "Post"
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :image,   presence: true
  validates :caption, presence: true
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  has_many :likes, :foreign_key => "liked_pics_id"
  has_many :who_liked, :through => :likes
  has_many :comments, :dependent => :destroy

  def self.followed_users_posts(user)
    self.all.select do |post|
      user.followed_users.include?(post.user)
    end
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }
  validates_attachment_content_type   :avatar, :content_type => /\Aimage\/.*\Z/
  has_many :posts,                    :dependent => :destroy
  has_many :likes,                    :foreign_key => "who_liked_id"
  has_many :comments,                 :dependent => :destroy
  has_many :liked_pics,               through: :likes
  has_many :relationships,            foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users,           through: :relationships, source: :followed
  has_many :reverse_relationships,    foreign_key: "followed_id",
                                      class_name:  "Relationship",
                                      dependent:   :destroy
  has_many :followers,                through: :reverse_relationships, source: :follower

  def like(post)
    self.likes.create(:liked_pics_id => post.id)
  end

  def following?(other_user)
    self.followed_users.include?(other_user)
  end

  def follow!(other_user)
    self.relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    self.relationships.find_by_followed_id(other_user.id).destroy
  end

  def self.search(query)
    where("email like ?", "%#{query}%") 
  end

  def username
    self.email.split("@")[0] #change later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :avatar) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save!
    redirect_to root_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])  
    end

    def comment_params
      params.require(:comment).permit(:body, :author, :post_id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:like][:liked_pics_id])
    current_user.like(@post)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render :file => "likes/toggle.js.erb" }
    end
  end

  def destroy
    like = Like.find(params[:id])
    @post = Post.find(like.liked_pics_id) 
    like.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render :file => "likes/toggle.js.erb" }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.followed_users_posts(current_user) + current_user.posts
  end

  def new
    @post = Post.create
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    @post.comments.create(:body => @post.caption, :user_id => @post.user_id)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def post_params
    params.require(:post).permit(:image, :caption)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed #user who was followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search]
      @users = User.search(params[:search])
    else
      @users = User.all
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" id="pnavbar">
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <div id="title-page">
            <ul class="nav navbar-nav">
              <li><a <%= link_to "HyperGram", root_path %></a></li>
              <li><a <%= link_to "new post", new_post_path %></a></li>
            </ul>
          </div>
          <div id="username-bar">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <% if request.original_url.include?("users/#{current_user.id}") %>
                  <li><a <%= link_to "logout", destroy_user_session_path, :method => :delete %></a></li>
                <% else %>
                  <li><a <%= link_to current_user.username, current_user %></a></li>
                <% end %>
              <% else %>
                <li><a <%= link_to "New account", new_user_registration_path %></a></li>
              <% end %>
            </ul>
          </div>
      </div>
    </div>
  </div>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <%= yield %>

</body>
</html>

app/views/likes/_like_buttom.html.erb
<% if like = current_user.likes.find_by_liked_pics_id(object.id) %>
  <%= form_for like, :html => { :method => :delete }, :remote => true do |f| %>
    <%= f.submit "unlike", :type => :image, :src => "/assets/r.png", class: "heart" %>
  <% end %>
<% else %>
  <%= form_for (current_user.likes.build(liked_pics_id: object.id)), :remote => true do |f| %>
    <div><%= f.hidden_field :liked_pics_id %></div>
    <%= f.submit "like", :type => :image, :src => "/assets/w5.png", class: "heart" %>
  <% end %>
<% end %>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/toggle.js.erb
$("#<%= @post.id %>").html("<%= escape_javascript render(:partial => 'like_buttom', :locals => { object: @post }) %>");
$("#<%= "likes" << @post.id.to_s %>").html("<%= escape_javascript pluralize(@post.who_liked.count, "like") %>")

app/views/posts/_comment_box.html.erb
<div class="actionBox">
  <%= form_for [object, Comment.new], :html => { :class => 'form-inline' } do |f| %>
    <div class="form-group">
      <%= f.text_field :body, placeholder: 'your comment...', class: "form-control", id: "cbox" %>
    </div>
    <%= f.submit "Add", class: "btn btn-default" %>
  <% end %>
</div>

app/views/posts/_indidual_post.html.erb
<% object.comments.each do |comment| %>
  <ul class="commentList" id="allComments">
    <li>
    <div class="commenterImage"><%= User.find(comment.user_id).username %></div>
    <div class="commentText"><%= comment.body %></div>
    <% if user_signed_in? && comment.user_id == current_user.id %>
      <div class="deleteComment"><%= link_to image_tag("delete.png", size: "11x8"), [object,comment], :method => :delete, data: { confirm: "Are you sure you want to delete this comment" } %>
    <% end %>
    </li>
  </ul>
<% end %>

app/views/posts/_like_buttom.html.erb
<% if like = current_user.likes.find_by_liked_pics_id(object.id) %>
  <%= form_for like, :html => { :method => :delete } do |f| %>
    <%= f.submit "Unlike", class: "btn btn-link" %>
  <% end %>
<% else %>
  <%= form_for (current_user.likes.build(liked_pics_id: object.id)) do |f| %>
    <div><%= f.hidden_field :liked_pics_id %></div>
    <%= f.submit "Like", class: "btn btn-link" %>
  <% end %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% @posts.each do |post| %>
        <div class="single-post">
          <div class="thumbnail">
            <div class="row">
              <div class="col-md-1">
                <div id="image-circle2">
                  <%= image_tag post.user.avatar.url(:medium) %> 
                </div>
              </div>
              <div class="col-md-1">
                <div id="name-on-post">
                  <%= link_to post.user.username, post.user%>
                </div>
              </div>
              <div class="col-md-2 col-md-offset-8">
                <div id="date-on-post">
                  <%= distance_of_time_in_words(post.created_at, 50.minutes.from_now).gsub('about', '')  %>
                </div>
              </div>
            </div>
            <%= image_tag post.image.url(:medium) %>
            <div class="likes_count" id="<%= "likes" << post.id.to_s %>"><%= pluralize(post.who_liked.count, "like") %></div>
            <div class= "heart-like" id="<%= post.id %>">
              <%= render 'likes/like_buttom', object: post %></li>
            </div>
            <%= render 'indidual_post', :object => post %>
            <%= render 'comment_box', :object => post %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @post do |f| %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.label :caption %>
      <p><%= f.text_field :caption, class: 'form-control' %></p>

      <p><%= f.submit "Submit picture", class: "btn btn-success center-block"  %></p>
    <% end %>
  </div>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/create.js.erb
$("#follow-form-users").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html("<%= @user.followers.count %>")

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/destroy.js.erb
$("#follow-form-users").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html("<%= @user.followers.count %>")

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(object.errors.count, "error") %> prohibited this form from being saved:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_edit.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Following", class: "btn btn-success", id: "unfollow-button" %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary", id: "follow-button" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Following", class: "btn btn-success", id: "unfollow-button" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="row">
    <div class="col-md-1">
      <div class="image-circle2">
        <%= image_tag user.avatar.url(:medium) %> 
      </div>
    </div>
    <div class="col-md-1" id="name-on-post">
      <%= link_to user.username, user%>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div id="user-main-page">
    <div class="row">
      <div class="col-md-3">
        <div id="image-circle">
          <%= image_tag @user.avatar.url(:medium) %>
        </div>
      </div>
      <div class="col-md-9">
        <div id="all-user-info">
          <div class="row">
            <div id="user-name">
              <%= @user.username %>
            </div>
            <div id="follow-form-users">
              <% unless current_user.id == @user.id %>
                <% if current_user.following?(@user) %>
                  <%= render 'unfollow' %>
                <% else %>
                  <%= render 'follow' %>
                <% end %>
              <% else %>
                <%= link_to "Edit profile", edit_user_registration_path, :id => "edit-button", class: "btn btn-success" %>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div id="user-email">
              <%= @user.email %>
            </div>
          </div>
          <div class="row">
            <div id="user-stats">
              <ul>
                <li><strong><%= @user.posts.count.to_s %></strong> Publications</li>
                <li><strong id="followers"><%= @user.followers.count.to_s %></strong> Followers</li>
                <li><strong><%= @user.followed_users.count.to_s %></strong> Following</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <% @user.posts.each do |post| %>
        <div class="col-md-4">
          <div id="indi-pic">
            <div class="thumbnail">
              <%= image_tag post.image.url(:medium) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>